<?php

return [
    'roles' => [
        'owner_manager' => [
            'label' => 'Dueño/Gerente',
            'default_home' => '/admin',
            'can_switch_branch' => true,
        ],
        'seller_cashier' => [
            'label' => 'Vendedor/Cajero',
            'default_home' => '/pos',
            'can_switch_branch' => false,
        ],
        'warehouse' => [
            'label' => 'Bodega/Inventarista',
            'default_home' => '/admin/products',
            'can_switch_branch' => false,
        ],
        'accounting' => [
            'label' => 'Contabilidad/Administración',
            'default_home' => '/admin',
            'can_switch_branch' => false,
        ],
        'technician' => [
            'label' => 'Técnico/Servicios',
            'default_home' => '/admin',
            'can_switch_branch' => false,
        ],
    ],

    'role_aliases' => [
        'admin' => 'owner_manager',
        'seller' => 'seller_cashier',
    ],

    'permissions' => [
        'dashboard.view',
        'pos.view',
        'pos.create_sale',
        'pos.change_price',
        'products.view',
        'products.create',
        'products.edit',
        'products.delete',
        'categories.view',
        'categories.create',
        'categories.edit',
        'categories.delete',
        'sales.view',
        'users.view',
        'users.manage',
        'clients.view',
        'clients.create',
        'clients.edit',
        'clients.delete',
        'cash.view',
        'cash.open',
        'cash.close',
        'cash.movements',
        'reports.view',
        'reports.export',
        'expenses.view',
        'expenses.create',
        'banks.view',
        'banks.movements',
        'inventory.view',
        'inventory.adjust',
        'inventory.series.manage',
        'sales.void',
        'sales.refund',
        'settings.view',
        'settings.update',
    ],

    'role_permissions' => [
        'owner_manager' => ['*'],
        'seller_cashier' => [
            'dashboard.view',
            'pos.view',
            'pos.create_sale',
            'products.view',
            'inventory.view',
            'sales.view',
            'clients.view',
            'clients.create',
            'clients.edit',
            'categories.view',
            'cash.view',
            'cash.open',
            'cash.close',
            'cash.movements',
        ],
        'warehouse' => [
            'dashboard.view',
            'products.view',
            'products.create',
            'products.edit',
            'categories.view',
            'categories.create',
            'categories.edit',
            'categories.delete',
            'inventory.view',
            'inventory.adjust',
            'inventory.series.manage',
        ],
        'accounting' => [
            'dashboard.view',
            'sales.view',
            'clients.view',
            'clients.edit',
            'clients.delete',
            'cash.view',
            'cash.open',
            'cash.close',
            'cash.movements',
            'reports.view',
            'reports.export',
            'expenses.view',
            'expenses.create',
            'banks.view',
            'banks.movements',
            'sales.void',
            'sales.refund',
            'settings.view',
        ],
        'technician' => [
            'dashboard.view',
            'products.view',
            'inventory.view',
            'inventory.series.manage',
            'sales.view',
        ],
    ],
];
